name = "Smithy"
version = "0.0.2"
authors = ["Josh Rutkowski <joshrutk@amazon.com>"]
description = "Smithy language support for Zed"
repository = "https://github.com/joshrutkowski/zed-smithy"
id = "smithy"
schema_version = 1
grammar = "smithy"
[grammars.smithy]
repository = "https://github.com/indoorvivants/tree-sitter-smithy"
commit = "8327eb84d55639ffbe08c9dc82da7fff72a1ad07"